version: '2'
services:
  
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=Catalino2023
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  odoo:
    image: odoo-16.0
    depends_on:
      - db
    ports:
      - 8069:8069
    tty: true
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=Catalino2023
    restart: always
    volumes:
      - ./odoo/extra-addons:/mnt/extra-addons
      - ./odoo/var/lib/odoo:/var/lib/odoo
      - ./odoo/etc/odoo:/etc/odoo

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=alejandrobrun@gmail.com
  #     - PGADMIN_DEFAULT_PASSWORD=Catalino2023
  #     - POSTGRES_USER=odoo
  #   depends_on:
  #     - db 
  #   ports:
  #     - 5432:80

  # portainer:
  #   image: portainer/portainer-ce:latest
  #   container_name: portainer
  #   restart: always
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./portainer/data:/data 
  #   ports:
  #     - 9000:9000
